# cluster specific values
cluster:
  # specify cluster name
  name: vsphere-cluster

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""

# specify s3 credential secret name
s3CredentialSecretName: ""
